BEGIN;

COMMENT ON TABLE public.customers IS 'Customer accounts and profiles for the e-commerce platform, including authentication state, contact details, loyalty data, preferences, and lifecycle timestamps.';
COMMENT ON COLUMN public.customers.id IS 'Auto-incrementing primary key for the customer.';
COMMENT ON COLUMN public.customers.uuid IS 'Globally unique public identifier for the customer.';
COMMENT ON COLUMN public.customers.email IS 'Unique email address used to identify and contact the customer.';
COMMENT ON COLUMN public.customers.password_hash IS 'Bcrypt-style password hash placeholder used for development data; never contains a plain-text password.';
COMMENT ON COLUMN public.customers.first_name IS 'Customer''s given name.';
COMMENT ON COLUMN public.customers.last_name IS 'Customer''s family name.';
COMMENT ON COLUMN public.customers.phone IS 'Customer''s contact telephone number.';
COMMENT ON COLUMN public.customers.date_of_birth IS 'Customer''s date of birth.';
COMMENT ON COLUMN public.customers.gender IS 'Customer gender code: M for male, F for female, or O for other.';
COMMENT ON COLUMN public.customers.is_active IS 'Whether the customer account is currently active.';
COMMENT ON COLUMN public.customers.is_verified IS 'Whether the customer''s account or email has been verified.';
COMMENT ON COLUMN public.customers.loyalty_points IS 'Current loyalty reward points accumulated by the customer.';
COMMENT ON COLUMN public.customers.preferences IS 'Customer preference JSON object. Observed keys and example values: theme (dark, light, auto), newsletter (true or false), and language (for example en, es, fr, de, ja, pt, it, ko). Use JSONB operators such as ->> when filtering by these keys.';
COMMENT ON COLUMN public.customers.metadata IS 'Customer segmentation and acquisition metadata stored as HSTORE. Observed keys and values: tier (bronze, silver, gold, platinum) and source (organic, referral, ads, social). Use HSTORE operators when querying these values.';
COMMENT ON COLUMN public.customers.created_at IS 'Timestamp when the customer account was created.';
COMMENT ON COLUMN public.customers.updated_at IS 'Timestamp when the customer account was last updated.';
COMMENT ON COLUMN public.customers.last_login_at IS 'Timestamp of the customer''s most recent login; NULL when no login is recorded.';
COMMENT ON COLUMN public.customers.deleted_at IS 'Soft-deletion timestamp; NULL means the account has not been soft deleted.';
COMMENT ON TABLE public.addresses IS 'Customer billing and shipping addresses.';
COMMENT ON COLUMN public.addresses.id IS 'Auto-incrementing primary key for the address.';
COMMENT ON COLUMN public.addresses.customer_id IS 'Customer who owns this address; references customers.id.';
COMMENT ON COLUMN public.addresses.address_type IS 'Purpose of the address: billing, shipping, or both.';
COMMENT ON COLUMN public.addresses.street_line1 IS 'Primary street address line.';
COMMENT ON COLUMN public.addresses.street_line2 IS 'Optional secondary address information such as apartment, unit, suite, or floor.';
COMMENT ON COLUMN public.addresses.city IS 'City of the address.';
COMMENT ON COLUMN public.addresses.state IS 'State, province, or regional subdivision.';
COMMENT ON COLUMN public.addresses.postal_code IS 'Postal or ZIP code.';
COMMENT ON COLUMN public.addresses.country IS 'Two-character country code; seeded data uses US.';
COMMENT ON COLUMN public.addresses.is_default IS 'Whether this is the customer''s default address for its address type.';
COMMENT ON COLUMN public.addresses.created_at IS 'Timestamp when the address record was created.';
COMMENT ON TABLE public.categories IS 'Hierarchical product categories. A category may reference another category as its parent.';
COMMENT ON COLUMN public.categories.id IS 'Auto-incrementing primary key for the category.';
COMMENT ON COLUMN public.categories.parent_id IS 'Parent category identifier for hierarchical categories; NULL indicates a top-level category.';
COMMENT ON COLUMN public.categories.name IS 'Human-readable category name.';
COMMENT ON COLUMN public.categories.slug IS 'Unique URL-friendly category identifier.';
COMMENT ON COLUMN public.categories.description IS 'Description of the products represented by the category.';
COMMENT ON COLUMN public.categories.image_url IS 'URL of the category image.';
COMMENT ON COLUMN public.categories.is_active IS 'Whether the category is currently available for use.';
COMMENT ON COLUMN public.categories.sort_order IS 'Display ordering within the category''s hierarchy level; lower values appear first.';
COMMENT ON COLUMN public.categories.created_at IS 'Timestamp when the category was created.';
COMMENT ON TABLE public.suppliers IS 'Product supplier and vendor contact records.';
COMMENT ON COLUMN public.suppliers.id IS 'Auto-incrementing primary key for the supplier.';
COMMENT ON COLUMN public.suppliers.company_name IS 'Supplier''s company or trading name.';
COMMENT ON COLUMN public.suppliers.contact_name IS 'Primary contact person at the supplier.';
COMMENT ON COLUMN public.suppliers.contact_email IS 'Primary supplier contact email address.';
COMMENT ON COLUMN public.suppliers.contact_phone IS 'Primary supplier contact telephone number.';
COMMENT ON COLUMN public.suppliers.address IS 'Supplier''s full postal address.';
COMMENT ON COLUMN public.suppliers.country IS 'Two-character country code for the supplier.';
COMMENT ON COLUMN public.suppliers.is_active IS 'Whether the supplier is currently active.';
COMMENT ON COLUMN public.suppliers.rating IS 'Supplier quality or performance rating from 0 to 5.';
COMMENT ON COLUMN public.suppliers.created_at IS 'Timestamp when the supplier record was created.';
COMMENT ON TABLE public.products IS 'Product catalog with pricing, category and supplier relationships, product attributes, media, ratings, and full-text search data.';
COMMENT ON COLUMN public.products.id IS 'Auto-incrementing primary key for the product.';
COMMENT ON COLUMN public.products.uuid IS 'Globally unique public identifier for the product.';
COMMENT ON COLUMN public.products.sku IS 'Unique stock-keeping unit used to identify the product.';
COMMENT ON COLUMN public.products.name IS 'Human-readable product name.';
COMMENT ON COLUMN public.products.slug IS 'Unique URL-friendly product identifier.';
COMMENT ON COLUMN public.products.description IS 'Detailed product description.';
COMMENT ON COLUMN public.products.short_description IS 'Brief product summary suitable for listings.';
COMMENT ON COLUMN public.products.category_id IS 'Category assigned to the product; references categories.id.';
COMMENT ON COLUMN public.products.supplier_id IS 'Supplier of the product; references suppliers.id.';
COMMENT ON COLUMN public.products.price IS 'Current customer-facing unit price before order-specific discounts.';
COMMENT ON COLUMN public.products.cost_price IS 'Internal acquisition or production cost per unit.';
COMMENT ON COLUMN public.products.compare_at_price IS 'Original or reference price used to show a discount relative to the current price.';
COMMENT ON COLUMN public.products.currency IS 'Three-character currency code for product prices; seeded data uses USD.';
COMMENT ON COLUMN public.products.weight_kg IS 'Product weight in kilograms.';
COMMENT ON COLUMN public.products.dimensions IS 'Physical dimensions stored as JSONB. Observed keys: length, width, height, and unit. Numeric measurements vary by product; unit is cm in the seeded data. Example: {"length": 16.5, "width": 7.8, "height": 0.8, "unit": "cm"}.';
COMMENT ON COLUMN public.products.is_active IS 'Whether the product is currently active and available in the catalog.';
COMMENT ON COLUMN public.products.is_featured IS 'Whether the product is highlighted as featured.';
COMMENT ON COLUMN public.products.is_digital IS 'Whether the product is digital rather than a physical item.';
COMMENT ON COLUMN public.products.tax_rate IS 'Default tax percentage applicable to the product.';
COMMENT ON COLUMN public.products.rating_avg IS 'Average rating calculated from approved reviews.';
COMMENT ON COLUMN public.products.rating_count IS 'Number of approved reviews included in rating_avg.';
COMMENT ON COLUMN public.products.tags IS 'Array of searchable product tags.';
COMMENT ON COLUMN public.products.attributes IS 'Category-specific product specifications stored as JSONB. Observed keys include color, storage, ram, screen_size, processor, display, type, connectivity, battery_life, driver_size, water_resistance, sensor, video, autofocus, stabilization, resolution, features, material, fit, care, sizes, occasion, cushioning, frame, cushions, seating, wheels, brakes, gears, pieces, includes, author, pages, isbn, and format. Keys vary by product category; inspect or filter only keys relevant to the product type.';
COMMENT ON COLUMN public.products.images IS 'JSONB array of product image objects. Each observed object contains url and alt keys. Example: [{"url": "https://cdn.example.com/products/phone-001-1.jpg", "alt": "Front view"}].';
COMMENT ON COLUMN public.products.search_vector IS 'PostgreSQL full-text search vector derived from searchable product text.';
COMMENT ON COLUMN public.products.created_at IS 'Timestamp when the product was created.';
COMMENT ON COLUMN public.products.updated_at IS 'Timestamp when the product was last updated.';
COMMENT ON TABLE public.inventory IS 'Inventory by product and warehouse. Available stock is quantity minus reserved_quantity. A product is low on stock when quantity is at or below reorder_level.';
COMMENT ON COLUMN public.inventory.id IS 'Auto-incrementing primary key for the inventory record.';
COMMENT ON COLUMN public.inventory.product_id IS 'Product whose stock is tracked; references products.id.';
COMMENT ON COLUMN public.inventory.warehouse_code IS 'Code identifying the warehouse or stock location.';
COMMENT ON COLUMN public.inventory.quantity IS 'Total physical quantity currently recorded at the warehouse.';
COMMENT ON COLUMN public.inventory.reserved_quantity IS 'Quantity reserved for pending or processing orders and not freely available.';
COMMENT ON COLUMN public.inventory.reorder_level IS 'Stock threshold at or below which replenishment should be considered.';
COMMENT ON COLUMN public.inventory.reorder_quantity IS 'Suggested quantity to add when replenishing stock.';
COMMENT ON COLUMN public.inventory.last_restocked_at IS 'Timestamp of the most recent stock replenishment.';
COMMENT ON COLUMN public.inventory.updated_at IS 'Timestamp when the inventory record was last updated.';
COMMENT ON TABLE public.orders IS 'Customer order headers. Join customers through customer_id and order_items through the composite key (id, created_at). The table is partitioned by created_at year. Use status to distinguish active, completed, cancelled, and refunded orders; exclude cancelled and refunded orders when calculating realized sales unless the question explicitly includes them.';
COMMENT ON COLUMN public.orders.id IS 'Order identifier. Together with created_at, forms the partitioned table primary key.';
COMMENT ON COLUMN public.orders.uuid IS 'Globally unique identifier for the order.';
COMMENT ON COLUMN public.orders.order_number IS 'Human-readable order number. Unique together with created_at.';
COMMENT ON COLUMN public.orders.customer_id IS 'Customer who placed the order; references customers.id.';
COMMENT ON COLUMN public.orders.status IS 'Order lifecycle status: pending, confirmed, processing, shipped, delivered, cancelled, or refunded.';
COMMENT ON COLUMN public.orders.payment_method IS 'Payment method: credit_card, debit_card, paypal, bank_transfer, cash, or crypto.';
COMMENT ON COLUMN public.orders.payment_status IS 'Current payment-processing state, such as pending, paid, failed, or refunded where present.';
COMMENT ON COLUMN public.orders.shipping_address_id IS 'Address used for shipment; references addresses.id.';
COMMENT ON COLUMN public.orders.billing_address_id IS 'Address used for billing; references addresses.id.';
COMMENT ON COLUMN public.orders.subtotal IS 'Order amount before tax, shipping, and order-level discounts.';
COMMENT ON COLUMN public.orders.tax_amount IS 'Total tax charged for the order.';
COMMENT ON COLUMN public.orders.shipping_amount IS 'Shipping or delivery charge for the order.';
COMMENT ON COLUMN public.orders.discount_amount IS 'Total order-level discount deducted from the order.';
COMMENT ON COLUMN public.orders.total_amount IS 'Final order amount after adding tax and shipping and subtracting discounts.';
COMMENT ON COLUMN public.orders.currency IS 'Three-character currency code for the order amounts; seeded data uses USD.';
COMMENT ON COLUMN public.orders.notes IS 'Optional free-text notes associated with the order.';
COMMENT ON COLUMN public.orders.metadata IS 'Additional order metadata stored as JSONB. Seeded values are mostly empty objects, so no stable business keys should be assumed. Inspect available keys before generating JSONB predicates.';
COMMENT ON COLUMN public.orders.ip_address IS 'IP address associated with the order request.';
COMMENT ON COLUMN public.orders.user_agent IS 'Client browser or application user-agent captured for the order.';
COMMENT ON COLUMN public.orders.created_at IS 'Timestamp when the order was placed. Also determines the table partition.';
COMMENT ON COLUMN public.orders.updated_at IS 'Timestamp when the order was last updated.';
COMMENT ON COLUMN public.orders.shipped_at IS 'Timestamp when the order was shipped; NULL until shipment.';
COMMENT ON COLUMN public.orders.delivered_at IS 'Timestamp when the order was delivered; NULL until delivery.';
COMMENT ON TABLE public.order_items IS 'Order line items. Join orders using both order_id = orders.id and order_created_at = orders.created_at because orders is partitioned with a composite key. Join products through product_id. Use quantity for units sold and total_price for line revenue.';
COMMENT ON COLUMN public.order_items.id IS 'Auto-incrementing primary key for the order line item.';
COMMENT ON COLUMN public.order_items.order_id IS 'Order identifier. Used with order_created_at to reference the partitioned orders table.';
COMMENT ON COLUMN public.order_items.order_created_at IS 'Creation timestamp of the referenced order; required as part of the composite foreign key.';
COMMENT ON COLUMN public.order_items.product_id IS 'Purchased product; references products.id.';
COMMENT ON COLUMN public.order_items.product_name IS 'Snapshot of the product name at the time of purchase.';
COMMENT ON COLUMN public.order_items.product_sku IS 'Snapshot of the product SKU at the time of purchase.';
COMMENT ON COLUMN public.order_items.quantity IS 'Number of product units purchased in this line item.';
COMMENT ON COLUMN public.order_items.unit_price IS 'Price per unit recorded for this order line before line-level calculations.';
COMMENT ON COLUMN public.order_items.discount_percent IS 'Percentage discount applied to this line item.';
COMMENT ON COLUMN public.order_items.tax_rate IS 'Tax percentage applied to this line item.';
COMMENT ON COLUMN public.order_items.total_price IS 'Extended total for the line item after its quantity, discount, and tax calculations.';
COMMENT ON COLUMN public.order_items.created_at IS 'Timestamp when the order line item was created.';
COMMENT ON TABLE public.reviews IS 'Customer reviews and ratings for products. Join products through product_id and customers through customer_id. Public product rating calculations should generally use only rows where is_approved is true.';
COMMENT ON COLUMN public.reviews.id IS 'Auto-incrementing primary key for the review.';
COMMENT ON COLUMN public.reviews.product_id IS 'Reviewed product; references products.id.';
COMMENT ON COLUMN public.reviews.customer_id IS 'Customer who submitted the review; references customers.id.';
COMMENT ON COLUMN public.reviews.order_id IS 'Order associated with the review when available.';
COMMENT ON COLUMN public.reviews.rating IS 'Customer rating from 1 to 5.';
COMMENT ON COLUMN public.reviews.title IS 'Short review headline.';
COMMENT ON COLUMN public.reviews.content IS 'Full review text.';
COMMENT ON COLUMN public.reviews.pros IS 'Array of positive aspects listed by the reviewer.';
COMMENT ON COLUMN public.reviews.cons IS 'Array of negative aspects listed by the reviewer.';
COMMENT ON COLUMN public.reviews.is_verified_purchase IS 'Whether the review is linked to a verified purchase.';
COMMENT ON COLUMN public.reviews.is_approved IS 'Whether the review has been approved for inclusion in public ratings.';
COMMENT ON COLUMN public.reviews.helpful_count IS 'Number of users who marked the review as helpful.';
COMMENT ON COLUMN public.reviews.images IS 'JSONB array containing review image data. Seeded rows may contain an empty array; do not assume a fixed object structure unless keys are observed in the data.';
COMMENT ON COLUMN public.reviews.created_at IS 'Timestamp when the review was submitted.';
COMMENT ON COLUMN public.reviews.updated_at IS 'Timestamp when the review was last updated.';

-- Views exposed to the Text-to-SQL assistant
COMMENT ON VIEW public.v_customer_summary IS 'Customer-level sales summary containing membership date, order counts, lifetime spending, average order value, latest order date, and loyalty points.';
COMMENT ON COLUMN public.v_customer_summary.customer_id IS 'Customer identifier from customers.id.';
COMMENT ON COLUMN public.v_customer_summary.email IS 'Customer email address.';
COMMENT ON COLUMN public.v_customer_summary.full_name IS 'Customer''s full name formed from first_name and last_name.';
COMMENT ON COLUMN public.v_customer_summary.member_since IS 'Timestamp when the customer account was created.';
COMMENT ON COLUMN public.v_customer_summary.total_orders IS 'Number of distinct non-cancelled and non-refunded orders placed by the customer.';
COMMENT ON COLUMN public.v_customer_summary.lifetime_value IS 'Total amount spent by the customer on non-cancelled and non-refunded orders.';
COMMENT ON COLUMN public.v_customer_summary.avg_order_value IS 'Average total amount of the customer''s non-cancelled and non-refunded orders.';
COMMENT ON COLUMN public.v_customer_summary.last_order_date IS 'Timestamp of the customer''s most recent non-cancelled and non-refunded order.';
COMMENT ON COLUMN public.v_customer_summary.loyalty_points IS 'Current loyalty reward points held by the customer.';

COMMENT ON VIEW public.v_product_inventory IS 'Product-level inventory summary combining catalog information with total, reserved, and available stock across warehouses.';
COMMENT ON COLUMN public.v_product_inventory.product_id IS 'Product identifier from products.id.';
COMMENT ON COLUMN public.v_product_inventory.sku IS 'Unique stock-keeping unit for the product.';
COMMENT ON COLUMN public.v_product_inventory.product_name IS 'Human-readable product name.';
COMMENT ON COLUMN public.v_product_inventory.price IS 'Current customer-facing unit price.';
COMMENT ON COLUMN public.v_product_inventory.category_name IS 'Name of the category assigned to the product.';
COMMENT ON COLUMN public.v_product_inventory.total_stock IS 'Total recorded inventory quantity across all warehouses.';
COMMENT ON COLUMN public.v_product_inventory.reserved_stock IS 'Total quantity reserved for pending or processing orders across all warehouses.';
COMMENT ON COLUMN public.v_product_inventory.available_stock IS 'Total stock available for sale, calculated as quantity minus reserved quantity.';
COMMENT ON COLUMN public.v_product_inventory.is_active IS 'Whether the product is currently active in the catalog.';
COMMENT ON COLUMN public.v_product_inventory.stock_status IS 'Derived stock state: out_of_stock, low_stock, or in_stock.';

COMMENT ON VIEW public.v_top_selling_products IS 'Product sales ranking containing order count, units sold, revenue, category, and rating metrics.';
COMMENT ON COLUMN public.v_top_selling_products.product_id IS 'Product identifier from products.id.';
COMMENT ON COLUMN public.v_top_selling_products.product_name IS 'Human-readable product name.';
COMMENT ON COLUMN public.v_top_selling_products.sku IS 'Unique stock-keeping unit for the product.';
COMMENT ON COLUMN public.v_top_selling_products.category_name IS 'Name of the category assigned to the product.';
COMMENT ON COLUMN public.v_top_selling_products.order_count IS 'Number of distinct orders containing the product.';
COMMENT ON COLUMN public.v_top_selling_products.units_sold IS 'Total number of product units sold across order items.';
COMMENT ON COLUMN public.v_top_selling_products.revenue IS 'Total line-item revenue generated by the product.';
COMMENT ON COLUMN public.v_top_selling_products.rating_avg IS 'Average approved customer rating for the product.';
COMMENT ON COLUMN public.v_top_selling_products.rating_count IS 'Number of approved reviews included in rating_avg.';

COMMIT;